### ISSUE TITLE
Snmp-set with 0 on number field does not work

### ISSUE THREAD

**Issue by JM2014** [iobroker-community-adapters/ioBroker.snmp#240] opened 2023-03-26 11:15 UTC
**Describe the bug**  
I am trying to set the snmp-value of an oid by doing a write via the iobroker-objects view. 
This is working fine for all values, except the 0. 
By looking into a wireshark trace it seems that "null" is transmitted instead. 

I tried this manually via snmpset and it is working as expected.
snmpset -v1 -c xxxxxx  192.168.178.19 .1.3.6.1.4.1.13742.6.4.1.2.1.2.1.4 i 0

**Expected behavior**  
I would expect, that a "0" is written.

**Versions:**  
    Platform: linux
    operating system: linux
    Architecture: x64
    CPUs: 2
    Speed: 2903 MHz
    Model: Common KVM processor
    RAM: 7.5 GB
    System uptime: 2 d. 04:25:44
    Node.js: v16.19.1
    time: 1679826469243
    timeOffset: -120
    adapters count: 561
    NPM: 8.19.3
    Disk size: 14.7 GB
    Disk free: 9.2 GB
    Uptime: 2 d. 03:59:26
    Active instances: 14
    Path: /opt/iobroker/
 - SNMP-Adapter version: 2.4.5
 - JS-Controller: 4.0.24
 
**Additional context**  
![objects](https://user-images.githubusercontent.com/6601967/227771587-872079ea-6542-4149-9774-453d72512ba0.png)
![OIDs](https://user-images.githubusercontent.com/6601967/227771588-cf0779e0-b838-4a4d-9c8f-6c98027fd0f5.png)
![Wireshark2](https://user-images.githubusercontent.com/6601967/227771592-de969e91-8fc5-4ca4-ad78-8d86f41e2206.png)
![EditObject](https://user-images.githubusercontent.com/6601967/227771794-e2088ebf-ab6d-41de-b8c9-e513908ed56f.png)

**Comment by mcm1957** [comment] 2023-03-26 17:12
@JM2014 Thanks for the very complet information provided with this issue.
A first review of the relevant ciode part did not show a problem.

I would ask to do the following things:

a) You seem to have three states with identical oid. I would ask to disable two of them. I'm not sure whether sending the same oid multiple times could cause troubles. (I do not really think this is the problem, as this ist not realted to 0 / non zero values, but trying this is not a big effort).

b) The decoded smnp data shown seems to be related to the get request which is issued after the set operation. Could you please check the iobroker logs and post the related liones? I think there should be en entry with either (or both) of session.set or session.get. In addition you write that snmpset worked. Did you check that a snmp read operation immediatly after the set works too? I only would like to double check that you device can handle the zero.

c) Is the decoded data from wireshark? As it seems to be a get(read) request could you try to capture the write (set) request too ?

d) Please activate the option "add raw states at tab Options
![image](https://user-images.githubusercontent.com/28575778/227792147-c2d54199-2fc8-4dcb-8d0a-9b4b5d12e574.png)
You should get a new state names *-raw after a normal successful read. Please provide the json stored within this data. (Please check for sensitive data - but I do not think there should be anys passwords or tokens within).

I'll try to reproduce the problem but I must first search for some snmp device which accepts numeric data for write.

Sorry that I cannot prpvide a fast fix.

**Comment by JM2014** [comment] 2023-03-26 18:39
Hi, first of all, thank you that you are looking for this problem!!!
a. I removed all, except one. 
b. + c.: I will add a wireshark. In this wireshark I tried the values: 5,0,6,0,7,8,0
Of course these values are not defined at the destination-device, but they should be send out. 
When looking at the trace it seems, that there are no SNMP-Sets with "0" send out. Do you have an idea here? 
 d: {"oid":"1.3.6.1.4.1.13742.6.4.1.2.1.2.1.4","type":2,"value":1}
 Greetings
 Juergen
![settings](https://user-images.githubusercontent.com/6601967/227796718-458672b8-6a39-467f-bf5a-2839c41ce203.png)
![raw](https://user-images.githubusercontent.com/6601967/227796722-8861c82c-9540-4eae-b11f-ef296c8ddba7.png)

**Comment by mcm1957** [comment] 2023-03-26 18:54
OK, 
a) duplicate OIDS can be skipped ass source of problem for sure now.
d) json looks like expected - no surprise

Please check wireshark traces. They seem to have been lost somewhere. At least I do not see any of them.

I do not have any idea why 0 should not be sent - but I will investigate further

**Comment by JM2014** [comment] 2023-03-26 18:58
I am doing the traces on a firewall between. But I can not see any reason, why it should drop the snmp-sets with "0". 
I will try to do a tcpdump tomorrow on the iobroker itself...But I would bet, that I will not see them there....that would mean, that the packets are not send out...,-)

**Comment by mcm1957** [comment] 2023-03-26 19:09
Please could you tray to capture debug logging
-) temporary disable all unrelated snmp devices to reduce the number of traceinfos written
-) disable all unrelated oids to reduce the number of traceinfos written
-) start adapter with debug logging
-) perform a write with "0" value

There should be a debug logged like
    onStateChange triggered - id ${pFullId} - with the id of the OID written

Please provide this trace and the following traces wi#hcih will log the processing of the value and teh called functions.

Thanks in advance

**Comment by mcm1957** [comment] 2023-03-26 19:25
I think I located the bug. Please do not set any further effrot at your side until I come back with more infos

**Comment by mcm1957** [comment] 2023-03-26 20:00
@JM2014 
Please retry new verion 2.4.6 available at github now and at latest at least tomorrow.
Please let me know if the problem is solved with the changes.

**Comment by JM2014** [comment] 2023-03-27 04:14
The new 2.4.6 is working fine. 
You solved the problem! Thankyou very much! Great!

**Comment by mcm1957** [comment] 2023-03-27 07:35
Fixed with 2.4.6

Problem prohibited setting of boolean false and empty string too.

**Closed by mcm1957** 2023-03-27 07:35 UTC
Labels: bug, fixed
