### ISSUE TITLE
Snmp-Write with 0 on Integer field does not work

### ISSUE THREAD

**Issue by JM2014** [iobroker-community-adapters/ioBroker.snmp#239] opened 2023-03-26 11:06 UTC
**Describe the bug**  
I am trying to change a snmp-value by doing a write via the iobroker-objects view. 
This is working fine for all values, except the 0. 

**To Reproduce**  

**Expected behavior**  
I would expect, that a "0" is written.

**Screenshots & Logfiles**  

**Versions:**  
    Platform: linux
    operating system: linux
    Architecture: x64
    CPUs: 2
    Speed: 2903 MHz
    Model: Common KVM processor
    RAM: 7.5 GB
    System uptime: 2 d. 04:25:44
    Node.js: v16.19.1
    time: 1679826469243
    timeOffset: -120
    adapters count: 561
    NPM: 8.19.3
    Disk size: 14.7 GB
    Disk free: 9.2 GB
    Uptime: 2 d. 03:59:26
    Active instances: 14
    Path: /opt/iobroker/
 - SNMP-Adapter version: 2.4.5
 - JS-Controller: 4.0.24
 
**Additional context**  
![objects](https://user-images.githubusercontent.com/6601967/227771587-872079ea-6542-4149-9774-453d72512ba0.png)
![OIDs](https://user-images.githubusercontent.com/6601967/227771588-cf0779e0-b838-4a4d-9c8f-6c98027fd0f5.png)
![Wireshark2](https://user-images.githubusercontent.com/6601967/227771592-de969e91-8fc5-4ca4-ad78-8d86f41e2206.png)

**Comment by mcm1957** [comment] 2023-03-26 16:20
seesm to be duplicate of #239

**Closed by mcm1957** 2023-03-26 16:20 UTC
